/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_H_RPCGEN
#define _LOG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct log_entry {
	char *username;
	char *operation;
	char *timestamp;
};
typedef struct log_entry log_entry;

#define LOG_PROG 0x20000001
#define LOG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SENDLOG 1
extern  void * sendlog_1(log_entry *, CLIENT *);
extern  void * sendlog_1_svc(log_entry *, struct svc_req *);
extern int log_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SENDLOG 1
extern  void * sendlog_1();
extern  void * sendlog_1_svc();
extern int log_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_entry (XDR *, log_entry*);

#else /* K&R C */
extern bool_t xdr_log_entry ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_H_RPCGEN */
