/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "log.h"

bool_t
xdr_log_entry (XDR *xdrs, log_entry *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, 512))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp, 32))
		 return FALSE;
	return TRUE;
}
