/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "log.h"

void *
sendlog_1_svc(log_entry *argp, struct svc_req *rqstp)
{
	/* Imprime: Nombre_usuario OPERACION TIMESTAMP */
    printf("%s %s %s\n",
           argp->username,
           argp->operation,
           argp->timestamp);
    fflush(stdout);
    /* Para que el wrapper llame a svc_sendreply, devolvemos un puntero no NULL */
    static char dummy; 
    return &dummy;
}
