/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TUPLAS_H_RPCGEN
#define _TUPLAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Coord {
	int x;
	int y;
};
typedef struct Coord Coord;

struct set_args {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	Coord value3;
};
typedef struct set_args set_args;

struct get_result {
	int status;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	Coord value3;
};
typedef struct get_result get_result;

struct modify_args {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	Coord value3;
};
typedef struct modify_args modify_args;

#define TUPLAS_PROG 0x31230000
#define TUPLAS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SET_VALUE 1
extern  int * set_value_1(set_args *, CLIENT *);
extern  int * set_value_1_svc(set_args *, struct svc_req *);
#define GET_VALUE 2
extern  get_result * get_value_1(int *, CLIENT *);
extern  get_result * get_value_1_svc(int *, struct svc_req *);
#define MODIFY_VALUE 3
extern  int * modify_value_1(modify_args *, CLIENT *);
extern  int * modify_value_1_svc(modify_args *, struct svc_req *);
#define DELETE_KEY 4
extern  int * delete_key_1(int *, CLIENT *);
extern  int * delete_key_1_svc(int *, struct svc_req *);
#define EXIST 5
extern  int * exist_1(int *, CLIENT *);
extern  int * exist_1_svc(int *, struct svc_req *);
#define DESTROY 6
extern  int * destroy_1(void *, CLIENT *);
extern  int * destroy_1_svc(void *, struct svc_req *);
extern int tuplas_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SET_VALUE 1
extern  int * set_value_1();
extern  int * set_value_1_svc();
#define GET_VALUE 2
extern  get_result * get_value_1();
extern  get_result * get_value_1_svc();
#define MODIFY_VALUE 3
extern  int * modify_value_1();
extern  int * modify_value_1_svc();
#define DELETE_KEY 4
extern  int * delete_key_1();
extern  int * delete_key_1_svc();
#define EXIST 5
extern  int * exist_1();
extern  int * exist_1_svc();
#define DESTROY 6
extern  int * destroy_1();
extern  int * destroy_1_svc();
extern int tuplas_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Coord (XDR *, Coord*);
extern  bool_t xdr_set_args (XDR *, set_args*);
extern  bool_t xdr_get_result (XDR *, get_result*);
extern  bool_t xdr_modify_args (XDR *, modify_args*);

#else /* K&R C */
extern bool_t xdr_Coord ();
extern bool_t xdr_set_args ();
extern bool_t xdr_get_result ();
extern bool_t xdr_modify_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TUPLAS_H_RPCGEN */
